# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_address_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='mobile',
            field=models.IntegerField(help_text='Your Mobile Number'),
        ),
    ]
