# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfeatured',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ProductFeatured',
        ),
    ]
