# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 11:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productfeatured'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=datetime.datetime(2018, 4, 20, 11, 6, 48, 586848, tzinfo=utc), upload_to=products.models.image_upload_to_category),
            preserve_default=False,
        ),
    ]
