# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimage',
            name='image',
            field=models.ImageField(upload_to='mediafiles/banners'),
        ),
    ]
