# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_auto_20180405_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='is_visible',
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='image',
            field=models.ImageField(upload_to='image_upload_to'),
        ),
    ]
