# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 11:13
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0004_auto_20180405_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='thumb',
            field=imagekit.models.fields.ProcessedImageField(upload_to='mediafiles'),
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='mediafiles'),
        ),
    ]
