# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0005_auto_20180405_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='description',
        ),
        migrations.RemoveField(
            model_name='album',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='album',
            name='thumb',
        ),
        migrations.RemoveField(
            model_name='albumimage',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='albumimage',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='albumimage',
            name='thumb',
        ),
    ]
