# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0006_auto_20180420_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumimage',
            name='default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Banner', to='banner.Album'),
        ),
    ]
