# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 14:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0007_albumimage_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumimage',
            name='title',
            field=models.CharField(default=datetime.datetime(2018, 4, 20, 14, 39, 53, 954769, tzinfo=utc), max_length=70),
            preserve_default=False,
        ),
    ]
