# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0008_albumimage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumimage',
            name='default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_category', to='banner.Album'),
        ),
    ]
