# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0012_auto_20180420_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank='False', null='False', upload_to='mediafiles'),
        ),
    ]
