# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0014_auto_20180421_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image_Image',
            new_name='image',
        ),
    ]
