# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 08:38
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_billingprofile_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='mobile_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
    ]
