# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_auto_20180510_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='mobile_no',
            field=models.IntegerField(),
        ),
    ]
