# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_emailactivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestemail',
            name='full_name',
            field=models.CharField(default='ajay mundhe', max_length=250),
            preserve_default=False,
        ),
    ]
