# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 08:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_productpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpurchase',
            name='order_id',
            field=models.CharField(default=datetime.datetime(2018, 4, 21, 8, 17, 4, 289022, tzinfo=utc), max_length=120),
            preserve_default=False,
        ),
    ]
