# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
